# Generated by Django 6.0.5 on 2026-09-10 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrats', '0001_initial'),
        ('demandes', '0001_initial'),
        ('paiements', '0001_initial'),
        ('sinistres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('DEMANDE_VALIDEE', 'Demande de contrat validée'), ('DEMANDE_REJETEE', 'Demande de contrat rejetée'), ('CONTRAT_CREE', 'Contrat créé'), ('CONTRAT_MODIFIE', 'Contrat modifié'), ('SINISTRE_TRAITE', 'Sinistre traité'), ('PAIEMENT_VALIDE', 'Paiement validé'), ('PAIEMENT_ECHOUE', 'Paiement marqué échoué'), ('PAIEMENT_REMBOURSE', 'Paiement remboursé')], max_length=30)),
                ('resume', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('contrat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='contrats.contrat')),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='demandes.demandecontrat')),
                ('paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='paiements.paiement')),
                ('sinistre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='sinistres.sinistre')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_journal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Entrée du journal d'activité",
                'verbose_name_plural': "Journal d'activité",
                'ordering': ['-date_creation'],
            },
        ),
    ]
