# Generated by Django 6.0.5 on 2026-05-11 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sinistre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sinistre', models.CharField(max_length=20, unique=True)),
                ('type_sinistre', models.CharField(choices=[('ACCIDENT', 'Accident'), ('VOL', 'Vol'), ('INCENDIE', 'Incendie'), ('MALADIE', 'Maladie'), ('DECES', 'Décès'), ('AUTRE', 'Autre')], max_length=20)),
                ('date_sinistre', models.DateField()),
                ('date_declaration', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('montant_reclame', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_indemnite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté'), ('REGLE', 'Réglé')], default='EN_ATTENTE', max_length=20)),
                ('document', models.FileField(blank=True, null=True, upload_to='sinistres/documents/')),
                ('commentaire', models.TextField(blank=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinistres', to='contrats.contrat')),
            ],
            options={
                'verbose_name': 'Sinistre',
                'verbose_name_plural': 'Sinistres',
                'ordering': ['-date_declaration'],
            },
        ),
    ]
