# Generated by Django 6.0.5 on 2026-09-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='cin',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CIN'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1),
        ),
        migrations.AlterField(
            model_name='client',
            name='ville',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
