# Generated by Django 6.0.5 on 2026-05-11 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrat', models.CharField(max_length=20, unique=True)),
                ('type_assurance', models.CharField(choices=[('AUTO', 'Assurance Auto'), ('SANTE', 'Assurance Santé'), ('HABITATION', 'Assurance Habitation'), ('VIE', 'Assurance Vie')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('montant_prime', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('EXPIRE', 'Expiré'), ('SUSPENDU', 'Suspendu'), ('RESILIE', 'Résilié')], default='ACTIF', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='contrats/documents/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='clients.client')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
                'ordering': ['-date_creation'],
            },
        ),
    ]
