# Generated by Django 6.0.5 on 2026-09-09 03:44

import demandes.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_alter_client_adresse_alter_client_cin_and_more'),
        ('contrats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_demande', models.CharField(max_length=20, unique=True)),
                ('type_assurance', models.CharField(choices=[('AUTO', 'Assurance Auto'), ('SANTE', 'Assurance Santé'), ('HABITATION', 'Assurance Habitation'), ('VIE', 'Assurance Vie')], max_length=20)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', max_length=20)),
                ('motif_rejet', models.TextField(blank=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_contrat', to='clients.client')),
                ('contrat', models.OneToOneField(blank=True, help_text='Contrat effectivement cree une fois la demande validee.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_origine', to='contrats.contrat')),
                ('demande_precedente', models.ForeignKey(blank=True, help_text='Demande rejetee que celle-ci resoumet, le cas echeant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resoumissions', to='demandes.demandecontrat')),
            ],
            options={
                'verbose_name': 'Demande de contrat',
                'verbose_name_plural': 'Demandes de contrat',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='DocumentDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('PIECE_IDENTITE', "Pièce d'identité"), ('CARTE_GRISE', 'Carte grise'), ('TITRE_PROPRIETE', 'Titre de propriété'), ('BAIL', 'Bail (contrat de location)')], max_length=20)),
                ('fichier', models.FileField(upload_to='demandes/documents/', validators=[demandes.validators.validate_document_file])),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='demandes.demandecontrat')),
            ],
            options={
                'verbose_name': 'Document de demande',
                'verbose_name_plural': 'Documents de demande',
                'ordering': ['date_upload'],
            },
        ),
    ]
